
server:
  port: 8010


kafka:
  bootstrap-servers: 192.168.99.100:9092
  topic:
    personEvent: dst.hs.kafkapoc.personevent

  
spring:

  application:    name: person-service

  datasource:
    name: MABPEOPLE    initialization-mode: embedded
    platform: h2
    url: jdbc:h2:mem:MABPEOPLE
    
    username: sa
    password: 
    driver-class-name: org.h2.Driver    
    
  jpa:
    show-sql: true
    hibernate:      ddl-auto: validate #create

  h2:
    console:      enabled: true
      path: "/h2" 
      

logging:
  level:
    org.springframework.data.rest.webmvc: WARN
             
